### ISSUE TITLE
Subdivision `parent_code`s are wrong as of latest update

### ISSUE THREAD

**Issue by eliasmistler** [pycountry/pycountry#186] opened 2023-12-14 16:10 UTC
I've just upgraded to version `23.12.11` and one of my scripts has failed now, because of `parent_code`s looking unexpected (and I presume wrong):

Specifically, I found this to be the case for GB subdivisions that are nested:

this:

```python
pycountry.subdivisions.get(code='GB-ENG')
```

correctly yields:

```python
SubdivisionHierarchy(code='GB-ENG', country_code='GB', name='England', parent_code=None, type='Country')
```

And similarly, this:

```python
pycountry.subdivisions.get(code='AZ-BAB')
```

yields:

```python
SubdivisionHierarchy(code='AZ-BAB', country_code='AZ', name='Babək', parent='NX', parent_code='AZ-NX', type='Rayon')
```

which means that I can run:

```python
child_subdivision = pycountry.subdivisions.get(code='AZ-BAB')
pycountry.subdivisions.get(code=child_subdivision.parent_code)
```

which correctly returns:

```python
SubdivisionHierarchy(code='AZ-NX', country_code='AZ', name='Naxçıvan', parent_code=None, type='Autonomous republic')
```

However, this does not work for GB subdivisions:

```python
pycountry.subdivisions.get(code='GB-BAS')
```

yields:

```python
SubdivisionHierarchy(code='GB-BAS', country_code='GB', name='Bath and North East Somerset', parent='GB-ENG', parent_code='GB-GB-ENG', type='Unitary authority')
```

But the correct code is `GB-ENG`, not `GB-GB-ENG`. So this fails:

```python
child_subdivision = pycountry.subdivisions.get(code='GB-BAS')
pycountry.subdivisions.get(code=child_subdivision.parent_code)
```
returns `None` (!)

**Comment by nschimmoller** [comment] 2023-12-14 18:06
@eliasmistler first and foremost thanks so much for the great code that we were able to include in the `23.12.11` release!

On a side note: I'm not sure if you'd be interesting in continuing to be involved in contribution and development of the pycountry database but I'm sure I speak for the other maintainers that we'd love any additional assistance we can get!

I believe that this is effectively the same issue as #17 but for different subdivisions.

I had added #17 to our Kanban Board for investigation / scoping but not yet sure exactly what the issue is that is causing this.

**Comment by nschimmoller** [comment] 2023-12-14 18:41
@eliasmistler 

I think I have a potential fix for this which I will add to the Kanban ticket. Within the SubdivisionHierarchy Class modify the __init__ code from 

Starting on line 172

``` python
         if self.parent_code is not None:
            self.parent_code = f"{self.country_code}-{self.parent_code}"
```

To instead be

``` python
        if self.parent_code is not None:
            # Split the parent_code to check if the country_code is already present
            parts = self.parent_code.split("-")
            if parts[0] != self.country_code:
                self.parent_code = f"{self.country_code}-{self.parent_code}"
```

Running the snippet that you provided now yields correct results

``` python
pycountry.subdivisions.get(code='GB-BAS')

SubdivisionHierarchy(code='GB-BAS', country_code='GB', name='Bath and North East Somerset', parent='GB-ENG', parent_code='GB-ENG', type='Unitary authority')
```

Additionally, and most importantly the code from #17 now returns no results

```
>>> [(i.code, i.parent_code) for i in pycountry.subdivisions if i.parent_code and not i.parent]
[]
 ```

I think this is a good fix. I will likely make a PR for this fix and add this last code snippet as a unit test

**Comment by eliasmistler** [comment] 2023-12-15 09:10
> On a side note: I'm not sure if you'd be interesting in continuing to be involved in contribution and development of the pycountry database but I'm sure I speak for the other maintainers that we'd love any additional assistance we can get!

@nschimmoller Thanks, appreciate the invite! Unfortunately I don't have a lot of time to offer, but it would be great to hear more about your vision for pycountry and what would be feasible for me to contribute.

**Comment by eliasmistler** [comment] 2023-12-15 09:12
@nschimmoller Regarding your fix, I think that looks reasonable, although it does look a bit like the problem is actually occuring earlier and this code is just patching over it 🤔

**Comment by nschimmo** [comment] 2023-12-15 09:26
@eliasmistler can you elaborate on where you think the issue originates

**Comment by nschimmo** [comment] 2023-12-15 12:33
@eliasmistler can you elaborate on where you think the issue originates

**Comment by nschimmoller** [comment] 2023-12-15 14:15
@eliasmistler apologies for any confusion from the prior response I was responding from GitHub mobile which is logged into my personal GitHub account. 

In regards to this Issue I have documented why I believe this to be the proper fix and the issue is not further up in the code [here](https://github.com/pycountry/pycountry/pull/187#discussion_r1428008348)

In regards to the vision for the project....

I believe the following is true for the different maintainers 

- ctheune originally wrote this library for a project he had at work in 2008 and with life and kids it has gone beyond what he is able to keep up with maintaining, especially as the need for this type of library is not one he encounters on a day to day basis
- zware was very helpful in pushing for ensuring pycountry supported Python 3.12 and ended support for Python<3.8

I personally view this as a project that I can learn a lot from in terms of Python Classes, Package Distribution, CI workflows, etc. However, my bread and butter is using python for Data Science and Analytics which does not give me a whole wealth of knowledge as it pertains to managing a code base. 

I would personally love to bring people in who have that experience, even if just for PR Review Purposes.

Tentative Roadmap:
1. Standardize method availability across various classes
    - People have asked for `search_fuzzy` functionality on languages, makes more sense to move to the Database Class and then allow the `ExistingCountries` `search_fuzzy` method override it's parent's
    - People use the `lookup` method in place of `search_fuzzy` for Classes lacking it today, and are frustrated that it stops when it finds the first match. `pycountry.languages.lookup("en")` returns the `En` language instead of `English`
2. Fix subdivisions `.get` searching. You cannot search by name of subdivisions using the `get` method
3. Introduce translation searching
    - When I started using this library in 2019 I wrote some local code that expanded the functionality of pycountry to allow for searching on foreign spellings of countries such as `Deutschland` instead of just `Germany`
4. Revamp `search_fuzzy` algorithim scoring
    - Users report unexpected behavior when using `pycountry.countries.search_fuzzy('Niger')` as it returns Nigeria above Niger

**Closed** 2023-12-16 18:47 UTC
Labels: bug
