### ISSUE TITLE
fuzzy_search and lookup fail for corner cases, ex. EIRE

### ISSUE THREAD

**Issue by thedeadliestcatch** [pycountry/pycountry#189] opened 2023-12-16 17:34 UTC
Hi,

Eire is often used as a localized reference for Ireland. Fuzzy search fails to acknowledge lack of tildes in localized representations of country names.

I have only found this to be the case for Ireland (for now), but it would be a nice thing to handle.

**Comment by nschimmoller** [comment] 2023-12-16 18:45
@thedeadliestcatch I don't think the issue is that Éire contains a tildes it's that as of today `pycountry` does not support localized looks of country names 

``` python
>>> pycountry.countries.search_fuzzy('Deutschland')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nate.schimmoller/Documents/GitHub/pycountry/src/pycountry/__init__.py", line 113, in search_fuzzy
    raise LookupError(query)
LookupError: deutschland
```

This is something that I have on our roadmap to investigate / consider implementing, but until we've had the chance to scope I don't want to commit to it yet. In the meantime I'm going to close this out as it is not a bug. 

I've added it on the initial enhancement request idea #111

**Closed by nschimmoller** 2023-12-16 18:45 UTC
